---
language: python
python: ["2.7", "3.3", "3.4", "3.5", "3.6"]
dist: trusty
sudo: false
cache:
  - pip
matrix:
  include:
    - python: "3.5"
      env: TOXENV=docs
    - python: "2.7"
      env: TOXENV=pre-commit
    - python: "3.5"
      env: TOXENV=pre-commit
    - python: "3.5"
      env: TOXENV=bandit

install:
    - pip install tox-travis | cat

script:
  - tox

notifications:
  email: false
